# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    monolog.logger.crawler:
#        class: Symfony\Bridge\Monolog\Logger
#        arguments: [crawler]
#        calls:
#             - [pushHandler, [@Monolog\Handler\StreamHandler]]


    monolog.logger.crawler:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [@logger]
#        tags:
#            - { name: monolog.logger, channel: crawler }
        calls:
            - [pushHandler, [@gf.logger_handler.crawler]]

    gf.logger_handler.crawler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.crawler.log, 100]
