<?php

namespace GraphNews\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserRepository extends EntityRepository
{
}
